### PR TITLE
Enable Dynamic Enabling / Disabling without External Feature Detection

### PR DESCRIPTION
**Pull request by asos-dominicjomaa**
# Detail
The library before any manual enabling performs a feature detection to check whether the `webkit` like scroll behaviour property even works, effectively checking if the library will be used at all or not:

```javascript
var testDiv = document.createElement('div');
document.documentElement.appendChild(testDiv);
testDiv.style.WebkitOverflowScrolling = 'touch';
var isScrollSupported = 'getComputedStyle' in window && window.getComputedStyle(testDiv)['-webkit-overflow-scrolling'] === 'touch';
document.documentElement.removeChild(testDiv);
```

This works well for situations where you only need this enabled once, but in our use case we need to be able to disable or enable iNoBounce only when a particular overlay is opened, which means this feature detection on the libraries IIFE construction is ignored. This coupled with the `0.1.6` version of the library seems to break Android scrolling entirely. The change here is to expose a boolean that can be rechecked when ever the consumer wishes to enable / disable the iNoBounce behaviour without worrying it will affect non-ios like devices.

As an example this might be used like this:
```javascript
[SHOW_FILTER_OVERLAY]: state => {
    if (iNoBounce.isScrollSupported) {
      iNoBounce.enable();
    }

    return { ...state, isFilterOverlayVisible: true };
},
[HIDE_FILTER_OVERLAY]: state => {
    if (iNoBounce.isScrollSupported) {
      iNoBounce.disable();
    }

   return { ...state, isFilterOverlayVisible: false };
},
```

### CODE REVIEW

**Comment by asos-dominicjomaa** [comment]
@lazd would love your thoughts on this!

**Comment by ethan-pearce** [comment]
This will super handy, looks great !

**Comment by lazd** [comment]
LGTM, thanks!

**Comment by lazd** [comment]
Released in 0.2.1!

**Comment by asos-dominicjomaa** [comment]
@lazd amazing turn around, thanks for the approval!

**Pull request merged**
