### PR TITLE
Allow zooming on iOS

### LINKED ISSUE #26: Enable zooming in iOS whilst keeping scrolling/bouncing disabled
0
down vote
favorite
I'm creating a web-app for iOS Safari and have run into a slight hurdle.

My web-app only takes up 1024x768 of screen real estate and therefore does not need scrolling, but it does need to be able to zoom (it's a PDF annotator).

I have used a plugin called iNoBounce (https://github.com/lazd/iNoBounce/) which successfully removes scrolling from the page by firing an evt.preventDefault() on the touchmove/touchstart events. This is great.

What this does though, is remove zoom events as well as scroll events. Is there a way to remove scrolling/elastic bouncing but to retain zoom on iOS safari?

Many thanks

---

I've managed to fix this issue, details here: http://stackoverflow.com/questions/37611300/ios-safari-disable-scroll-bounce-but-retain-zoom/37612533#37612533

### PR DESCRIPTION
**Pull request by benface**
This fixes #26.

### CODE REVIEW

**Comment by lazd** [comment]
This looks simple enough... Does it impact non-zooming usage at all?

**Comment by benface** [comment]
Not in my tests. Note that it disables the behaviour of preventing bouncing when the page is zoomed in, because I found it caused unexpected and buggy behaviour (it made it really hard to zoom back out for some reason).

**Comment by benface** [comment]
Hey @lazd, do you have any questions about this PR?

**Comment by lazd** [comment]
Hey @benface I think it's good to go.

**Comment by rafecolton** [comment]
@lazd this is still an issue on iOS 12.2. Verified in the simulator on http://blog.lazd.net/iNoBounce/

**Pull request merged**
