### PR TITLE
Allow horizontal scrolling

### PR DESCRIPTION
**Pull request by santiDotIO**
Added some logic to allow horizontal scrolling 

css properties to enable:
```
overflow-y: hidden;
overflow-x: scroll;
-webkit-overflow-scrolling: touch;
-webkit-box-flex: 1;
```

P.S. Thank you for this library it helped me out a lot on a web app with strict scrolling sections!!!

### CODE REVIEW

**Comment by lazd** [comment]
Hey thanks for your contribution!

Does the bounce prevention behavior still work as it did before without modifying CSS?

How widely has the fix been tested? Does it break Android?

**Comment by santi6291** [comment]
Hi there, This is pretty well tested. I haven't tested it on android. just OSX browsers and iOS. I can run some more test later this weeks

best,
santiago

**Comment by izumskee** [comment]
Hi! This PR looks very helpful for me. Thanks @santi6291.

**Comment by lazd** [comment]
@izumskee awesome, can you pull the code and test it in your current web app that uses iNoBounce and report back on what you had to do to upgrade and any problems you ran into?

**Comment by santi6291** [comment]
@izumskee if you could do that it be great. I been really busy and won't be able to do some in-depth testing for some time.

**Comment by izumskee** [comment]
Sure, guys. I'll do it in the next few days.

**Comment by izumskee** [comment]
Hi, guys! I've tested this PR and it works pretty well in my web app on iOS and Android.

**Comment by lazd** [comment]
@izumskee good to hear! Any quirks or changes you had to make?

**Comment by izumskee** [comment]
@lazd no, it works well for me.

**Comment by izumskee** [comment]
@lazd no, it works well for me.

**Comment by lazd** [comment]
@izumskee did you test in iOS 10.3?

**Comment by santi6291** [comment]
@lazd We I did this work I tested primarily on 10.3. I confirm it works fine.

**Comment by lazd** [comment]
@santi6291 thanks, got an issue #37 that that iNoBounce doesn't work at all in 10.3, so I was wondering if you had tested this in 10.3 yet. Thanks!

**Comment by santi6291** [comment]
Very strange, It worked on iOS 10.3(iPad) before modifying too.

**Comment by lazd** [comment]
@santi6291 thanks for the insight, it's likely just a bug in the dev's code. I can't update to 10.3 over here as I'm stuck on XCode 8.2 on my machine and it only supports 10.2, heh

**Comment by santi6291** [comment]
@lazd Hi there just wanted to follow up on this?

**Comment by lazd** [comment]
@santi6291 I don't have time to give it a proper review right now, but I will take a look next week. Thanks!

**Comment by santi6291** [comment]
@lazd any updates when this will get merged?

**Comment by zhonghuiwen** [comment]
@santi6291 Thank you so much! it works on iOS 11!

**Comment by terpro** [comment]
@santi6291 This works perfectly, thanks! How is it not merged yet?

**Comment by santi6291** [comment]
@zhonghuiwen, @terpro Glad to hear this has been working out great for you guys! Not sure when it will get merged 😞

**Comment by topaxi** [comment]
@lazd any way I can help to get this merged?

**Comment by lazd** [comment]
There are no examples in the repo to test this with, and as I don't use this lib in any active projects, I have no place to test it. I haven't had time to get around to adding an example so I can verify the fix works, I guess I'll have to go ahead and do that.

**Comment by lazd** [comment]
I'm not sure what the expected behavior is here, but I did the work and added an example to test it, and it doesn't work the way I would expect it to at all -- now the app bounces side to side when scrolling, and worse, it also bounces up and down if combined with a side scroll.

This is a very hard problem to solve, and the point of this library is to not bounce, at all, so without a solution that prevents bouncing side to side as well as up and down, I can't merge this.

**Comment by lazd** [comment]
@terpro, you reported this works perfectly. Can you describe the behavior you're seeing, as well as provide an example where it works? Please look at [my example](https://github.com/lazd/iNoBounce/blob/master/examples/horiz.html) and let me know how it differs from your usage.

**Comment by santi6291** [comment]
@lazd The main goal here is to allow horizontal scrolling. There is control over which direction to allow scrolling, by toggling the overflow `hidden` / `scroll ` properties for either `overflow-y` or `overflow-x`. Will try to take a look at disabling the horizontal bounce effect

**Comment by lazd** [comment]
@santi6291 ok, so it's exclusive -- you can't have both horizontal and vertical scrolling. I did not test disabling `overflow-y` as I was rushing, can you please rebase and update the example to include that?

**Comment by santi6291** [comment]
I can certainly update with more details, Although I think you should be able to scroll both directions. If the main goal is to disallow the bounce effect on iOS why not allow scrolling both directions?
This PR allows for no scrolling, vert scroll only, horiz scroll only or both directions.

**Comment by lazd** [comment]
Perhaps my example is flawed then, but I was experiencing bounces when scrolling with both directions.

**Comment by santi6291** [comment]
Just to clarify it should not bounce either direction but scrolling should be possible. I'll take a look at making sure bouncing is not happening

**Comment by terpro** [comment]
For my usage, I did not have both horizontal and vertical scrolling at the same time. (I had horizontally scrolling divs within vertically scrolling ones). Horizontal scrolling didn't work at all until I used the code here. I haven't tested in other scenarios.

**Comment by zhonghuiwen** [comment]
@santi6291 i've adapted your horizontal scrolling code to work on the latest ios 11.3+ here https://github.com/lazd/iNoBounce/pull/53. Thanks for your fantastic work

**Pull request closed without merging**
