### PR TITLE
Update inobounce.min.js to v0.1.3

### PR DESCRIPTION
**Pull request by Piicksarn**
Use http://marijnhaverbeke.nl/uglifyjs for minifying inobounce.js@0.1.3

### CODE REVIEW

**Comment by lazd** [comment]
I'm actually -1 for this. IMO the minified file should be removed from the repository completely. It is my opinion that the minification should be done by implementors as part of their build process or should only be included as part of the release.

**Comment by lazd** [comment]
I just saw https://github.com/cdnjs/cdnjs/issues/9047 and now understand the motivation behind your PR. However, I will close it, add minification as a npm script before release, and perform a new release with the correct minified files.

**Comment by lazd** [comment]
Alright, the minified file is updated, 0.1.3 has been properly tagged and released on Github and npm.

Thanks for bringing this issue to my attention!

**Comment by Piicksarn** [comment]
@lazd, thanks for your great work and efficient reply 😄

**Pull request closed without merging**
