### PR TITLE
Fix #2 issue: horizontal can't scrolling

### LINKED ISSUE #2: Horizontal scrolling not possible when vertically scrolled to top or bottom
If an element allows both horizontal and vertical scrolling, it is not possible to scroll horizontally if the element is scrolled to either the top or bottom.

### PR DESCRIPTION
**Pull request by RoberMac**
Fix [#2](https://github.com/lazd/iNoBounce/issues/2) issue: horizontal can't scrolling

### CODE REVIEW

**Comment by lazd** [comment]
@RoberMac this is definitely along the lines of the solution I had in mind. I need some time to review this and test it manually as iNoBounce doesn't have tests (how do you test that?!).

Thanks for the contribution, I'll get back with you once I'd had a chance to thoroughly poke at it!

**Comment by rayshan** [comment]
Nudge nudge, any luck folks?

**Comment by lazd** [comment]
@RoberMac, can you rebase?

**Comment by RoberMac** [comment]
@lazd OK

**Comment by lazd** [comment]
@RoberMac I merged your fix, but it doesn't seem the issue was solved. I reverted the merge and added an example that shows the problem.

**Comment by fenixi0** [comment]
It seems this is unresolved yet. Any fix?

**Pull request merged**
